from __future__ import annotations

from pathlib import Path
import re

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from .boxplots import (
    category_legend,
    finish,
    measure_panel,
    panel_size,
    scale_text,
)
from .config import measure_label, rank_scale_case_column, validate_rank_sort
from .signals import summarize_grouped_signal_comparisons


def _safe_name(value: object) -> str:
    result = re.sub(r"[^a-zA-Z0-9._-]+", "-", str(value).strip()).strip("-_.").lower()
    return result or "value"


# The boxplot pools one point per case -- one task, dataset, architecture, and
# functional similarity measure, with its seeds and layer models already
# averaged into that one point -- exactly as the domain summary does, so it
# follows the same `rank_scale`.
RANK_AXIS_LABELS = {
    "mean_normalized_rank": "Mean normalized rank per case (0 = best, 1 = worst)",
    "mean_rank": "Mean rank per case (1 = best)",
}


MEAN_SORT_SUFFIX = "_mean"


def plot_rank_boxplots(
    case_ranks: pd.DataFrame,
    out_path: Path,
    *,
    rank_scale: str | None = None,
    rank_sort: str | None = None,
    box_style: str | None = None,
) -> list[Path]:
    """The configured-sort rank boxplot, plus a mean-sorted companion.

    The reported sort is the unfavourable tail (`quantile90`), which answers
    "how badly does this measure do when it does badly". The mean answers
    "where does it land on average", and the two disagree exactly when a
    measure is usually good and occasionally terrible -- which is worth seeing
    rather than choosing between. Writing both means neither has to be
    regenerated by hand from `per_case_ranks.csv` to be looked at.

    The companion is skipped when the configured sort is already `mean`, so the
    two files are never the same figure under two names.
    """
    written: list[Path] = []
    plot_rank_boxplot(
        case_ranks,
        out_path,
        rank_scale=rank_scale,
        rank_sort=rank_sort,
        box_style=box_style,
    )
    if out_path.is_file():
        written.append(out_path)
    if validate_rank_sort(rank_sort) == "mean":
        return written
    mean_path = out_path.with_name(
        f"{out_path.stem}{MEAN_SORT_SUFFIX}{out_path.suffix}"
    )
    plot_rank_boxplot(
        case_ranks,
        mean_path,
        rank_scale=rank_scale,
        rank_sort="mean",
        box_style=box_style,
    )
    if mean_path.is_file():
        written.append(mean_path)
    return written


def plot_rank_boxplot(
    case_ranks: pd.DataFrame,
    out_path: Path,
    *,
    rank_scale: str | None = None,
    rank_sort: str | None = None,
    box_style: str | None = None,
) -> None:
    """One box per measure, pooling one point per case.

    Drawing, ordering, colouring, and the legend all come from `boxplots`, so
    this figure cannot drift from the cross-domain ones -- which it did, having
    grown a fixed 10-inch width and a right-hand legend that stole from it.
    """
    column = rank_scale_case_column(rank_scale)
    if case_ranks.empty:
        return
    fig, ax = plt.subplots(figsize=panel_size(case_ranks["metric"].nunique()))
    drawn = measure_panel(
        ax,
        case_ranks,
        column,
        higher_is_better=False,
        rank_sort=rank_sort,
        box_style=box_style,
    )
    if not drawn:
        plt.close(fig)
        return
    ax.set_xlabel(RANK_AXIS_LABELS[column])
    ax.set_ylabel("Similarity measure")
    category_legend(fig, drawn, rank_sort=rank_sort, box_style=box_style)
    finish(fig, out_path)


def plot_quality_heatmaps(values: pd.DataFrame, out_dir: Path) -> list[Path]:
    outputs: list[Path] = []
    finite = values[np.isfinite(values["value"])].copy()
    if finite.empty:
        return outputs
    out_dir.mkdir(parents=True, exist_ok=True)
    group_columns = ["quality_measure", "functional_similarity_measure"]
    for (quality, functional), group in finite.groupby(
        group_columns, dropna=False, sort=True
    ):
        matrix = group.pivot_table(
            index="metric", columns="architecture", values="value", aggfunc="mean"
        )
        if matrix.empty:
            continue
        matrix = matrix.sort_index().sort_index(axis=1)
        width = max(6.0, 1.1 * len(matrix.columns) + 3.0)
        height = max(4.0, 0.32 * len(matrix.index) + 2.0)
        fig, ax = plt.subplots(figsize=(width, height))
        quality_text = str(quality)
        if quality_text == "violation_rate":
            cmap, vmin, vmax = "viridis_r", 0.0, 1.0
        elif "corr" in quality_text.lower() or quality_text.lower().endswith("tau"):
            cmap, vmin, vmax = "coolwarm", -1.0, 1.0
        else:
            cmap, vmin, vmax = "viridis", 0.0, 1.0
        image = ax.imshow(
            matrix.to_numpy(dtype=float), aspect="auto", cmap=cmap, vmin=vmin, vmax=vmax
        )
        ax.set_xticks(np.arange(len(matrix.columns)))
        ax.set_xticklabels(matrix.columns, rotation=35, ha="right")
        ax.set_yticks(np.arange(len(matrix.index)))
        # Named the way every other figure names a measure. The matrix keeps
        # the raw index, so only the printed axis changes.
        ax.set_yticklabels([measure_label(name) for name in matrix.index])
        title = quality_text
        functional_text = "" if pd.isna(functional) else str(functional)
        if functional_text:
            title = f"{title} · {functional_text}"
        ax.set_title(title)
        ax.set_xlabel("Architecture")
        ax.set_ylabel("Similarity measure")
        fig.colorbar(image, ax=ax, fraction=0.025, pad=0.02)
        fig.tight_layout()
        suffix = f"__{_safe_name(functional_text)}" if functional_text else ""
        path = out_dir / f"{_safe_name(quality_text)}{suffix}.png"
        scale_text(fig)
        fig.savefig(path, dpi=180)
        plt.close(fig)
        outputs.append(path)
    return outputs


def plot_auprc_vs_violation_rate(values: pd.DataFrame, out_path: Path) -> Path | None:
    finite = values[np.isfinite(values["value"])].copy()
    finite = finite[finite["quality_measure"].isin({"AUPRC", "violation_rate"})]
    if finite.empty:
        return None
    keys = ["source", "architecture", "observation_id", "metric"]
    paired = finite.pivot_table(
        index=keys, columns="quality_measure", values="value", aggfunc="mean"
    )
    if not {"AUPRC", "violation_rate"}.issubset(paired.columns):
        return None
    paired = paired.dropna(subset=["AUPRC", "violation_rate"]).reset_index()
    if paired.empty:
        return None
    fig, ax = plt.subplots(figsize=(7, 5))
    styles = {
        "baseline": ("#7f7f7f", "o"),
        "manifold": ("#d55e00", "^"),
    }
    for source, group in paired.groupby("source", sort=True):
        color, marker = styles.get(str(source), ("#4c78a8", "o"))
        ax.scatter(
            group["violation_rate"],
            group["AUPRC"],
            label=str(source),
            color=color,
            marker=marker,
            alpha=0.75,
            edgecolors="none",
        )
    ax.set_xlabel("Violation rate (lower is better)")
    ax.set_ylabel("AUPRC (higher is better)")
    ax.grid(alpha=0.2)
    ax.legend(frameon=False)
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    scale_text(fig)
    fig.savefig(out_path, dpi=180)
    plt.close(fig)
    return out_path


def plot_signal_groups(
    by_seed: pd.DataFrame, grouped: pd.DataFrame, out_dir: Path
) -> list[Path]:
    if grouped.empty:
        return []
    out_dir.mkdir(parents=True, exist_ok=True)
    pair_column = (
        "condition_pair" if "condition_pair" in grouped.columns else "setting_pair"
    )
    seed_column = (
        "condition_seed_pair"
        if "condition_seed_pair" in by_seed.columns
        else "seed_pair"
    )
    keys = [
        "domain",
        "benchmark",
        "dataset",
        "metric",
        "architecture_pair",
        pair_column,
        "param_name",
    ]
    outputs: list[Path] = []
    for key, summary in grouped.groupby(keys, dropna=False, sort=True):
        selector = pd.Series(True, index=by_seed.index)
        for column, value in zip(keys, key):
            selector &= by_seed[column].fillna("").astype(str) == (
                "" if pd.isna(value) else str(value)
            )
        seeds = by_seed[selector]
        fig, ax = plt.subplots(figsize=(7, 4.5))
        for _, curve in seeds.groupby(seed_column, sort=True):
            curve = curve.sort_values("param_value")
            ax.plot(
                curve["param_value"],
                curve["score"],
                color="#4c78a8",
                alpha=0.25,
                linewidth=1,
            )
        summary = summary.sort_values("param_value")
        x = summary["param_value"].to_numpy(dtype=float)
        mean = summary["mean_score"].to_numpy(dtype=float)
        std = summary["std_score"].fillna(0).to_numpy(dtype=float)
        ax.plot(x, mean, color="#d55e00", linewidth=2.2, label="seed-pair mean")
        ax.fill_between(
            x, mean - std, mean + std, color="#d55e00", alpha=0.2, label="±1 SD"
        )
        if bool(summary["logscale"].fillna(False).any()) and np.all(x > 0):
            ax.set_xscale("log")
        ax.set_xlabel(str(key[-1]))
        ax.set_ylabel("Similarity")
        ax.set_title(f"{measure_label(key[3])} · {key[4]} · {key[5]}")
        ax.grid(alpha=0.2)
        ax.legend(frameon=False)
        fig.tight_layout()
        safe = "__".join(_safe_name(value) for value in key)
        path = out_dir / f"{safe}.png"
        scale_text(fig)
        fig.savefig(path, dpi=180)
        plt.close(fig)
        outputs.append(path)
    return outputs


def plot_grouped_signal_comparisons(signals: pd.DataFrame, out_dir: Path) -> list[Path]:
    summary = summarize_grouped_signal_comparisons(signals)
    if summary.empty:
        return []

    out_dir.mkdir(parents=True, exist_ok=True)
    plot_keys = [
        "domain",
        "benchmark",
        "dataset",
        "metric",
        "architecture",
        "param_name",
    ]
    outputs: list[Path] = []
    for key, group in summary.groupby(plot_keys, dropna=False, sort=True):
        condition_pairs = sorted(group["condition_pair"].dropna().astype(str).unique())
        if not condition_pairs:
            continue
        if len(condition_pairs) <= 10:
            cmap = plt.get_cmap("tab10")
        elif len(condition_pairs) <= 20:
            cmap = plt.get_cmap("tab20")
        else:
            cmap = plt.get_cmap("viridis")

        fig, ax = plt.subplots(figsize=(8, 5))
        for index, condition_pair in enumerate(condition_pairs):
            curve = group[
                group["condition_pair"].astype(str).eq(condition_pair)
            ].sort_values("param_value")
            x = curve["param_value"].to_numpy(dtype=float)
            mean = curve["mean_score"].to_numpy(dtype=float)
            std = curve["std_score"].fillna(0).to_numpy(dtype=float)
            color = cmap(index / max(len(condition_pairs) - 1, 1))
            ax.plot(
                x,
                mean,
                color=color,
                marker="o",
                linewidth=1.8,
                markersize=3.2,
                label=condition_pair,
            )
            ax.fill_between(x, mean - std, mean + std, color=color, alpha=0.18)

        if bool(group["logscale"].any()) and bool((group["param_value"] > 0).all()):
            ax.set_xscale("log")
        ax.set_xlabel(str(key[-1]))
        ax.set_ylabel("Similarity")
        ax.set_title(
            f"{measure_label(key[3])}: {key[4]}-vs-{key[4]} "
            "condition-pair mean +/- SD"
        )
        ax.grid(alpha=0.2)
        ax.legend(fontsize=7, title="condition pair", frameon=False)
        fig.tight_layout()
        safe = "__".join(_safe_name(value) for value in key)
        path = out_dir / f"grouped_signals__{safe}__condition-pairs.png"
        scale_text(fig)
        fig.savefig(path, dpi=180)
        plt.close(fig)
        outputs.append(path)
    return outputs


__all__ = [
    "plot_auprc_vs_violation_rate",
    "plot_grouped_signal_comparisons",
    "plot_quality_heatmaps",
    "plot_rank_boxplot",
    "plot_rank_boxplots",
    "plot_signal_groups",
]
